dependencies:
  - python=3.8
  - pip:
    absl-py==0.15.0
    ale-py==0.7.4
    astunparse==1.6.3
    autorom==0.4.2
    autorom-accept-rom-license==0.4.2
    cachetools==5.0.0
    clang==5.0
    click==8.1.2
    cloudpickle==2.0.0
    cycler==0.11.0
    flatbuffers==1.12
    fonttools==4.32.0
    gast==0.4.0
    google-auth==2.6.2
    google-auth-oauthlib==0.4.6
    google-pasta==0.2.0
    grpcio==1.44.0
    gym==0.23.1
    gym-notices==0.0.6
    h5py==3.1.0
    imageio==2.16.2
    importlib-metadata==4.11.3
    importlib-resources==5.6.0
    jsanimation==0.1
    keras-preprocessing==1.1.2
    kiwisolver==1.4.2
    markdown==3.3.6
    matplotlib==3.5.1
    networkx==2.8
    numpy==1.19.5
    oauthlib==3.2.0
    opt-einsum==3.3.0
    pillow==9.1.0
    protobuf==3.20.0
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
    pyparsing==3.0.7
    pywavelets==1.3.0
    requests-oauthlib==1.3.1
    rsa==4.8
    scikit-image==0.19.2
    scipy==1.8.0
    six==1.15.0
    tensorboard==2.8.0
    tensorboard-data-server==0.6.1
    tensorboard-plugin-wit==1.8.1
    tensorflow==2.6.0
    tensorflow-estimator==2.8.0
    termcolor==1.1.0
    tifffile==2022.4.8
    tqdm==4.64.0
    typing-extensions==3.7.4.3
    werkzeug==2.1.1
    wrapt==1.12.1
    zipp==3.8.0


############
