
solaris_hyp = {
    "EPSILON_START":0.9, 
    "EPSILON_DECAY_RATE":0.95,
    "EPSILON_MIN":0.001,
    "EPSILON_DECAY_BOOL":True,

    "BUFFER_SIZE":20000,
    "BATCH_SIZE":32,
    "EPs":2000,

    # "CONV_LAYERS":5,
    # "DROPOUT":0.2,
    "INIT_LEARNING_RATE":0.001,
}